[package]
org = "wso2healthcare"
name = "testObservation_0.1.5"
version = "0.1.5"
export = ["testObservation_0.1.5"]
distribution = "2201.3.1"
authors = ["WSO2 Healthcare"]
keywords = ["Healthcare","FHIR","Observation","r4","international"]

[build-options]
observabilityIncluded = true
